version: "1"

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - ineffassign
    - typecheck
    - bodyclose
    - gocritic
    - gocyclo
    - misspell
    - prealloc
    - unconvert
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 10

run:
  tests: false
  timeout: 5m

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go$
      linters:
        - gocyclo
    - text: "cyclomatic complexity"
      linters:
        - gocyclo